spring.application.name=usersApp
server.port=9292

# OracleDB connection settings
spring.datasourse.schema=DB_DEVELOPER
spring.datasource.url=jdbc:oracle:thin:@localhost:1521/XE
spring.datasource.username=DB_DEVELOPER
spring.datasource.password=1234
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver


# HikariCP settings
spring.datasource.hikari.minimumIdle=5
spring.datasource.hikari.maximumPoolSize=20
spring.datasource.hikari.idleTimeout=30000
spring.datasource.hikari.maxLifetime=2000000
spring.datasource.hikari.connectionTimeout=30000
spring.datasource.hikari.poolName=HikariPoolBooks

# JPA settings
#spring.jpa.database-platform=org.hibernate.community.dialect.Oracle12cDialect
#spring.jpa.hibernate.use-new-id-generator-mappings=false 
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
logging.level.org.hibernate.SQL=debug

logging.level.org.springframework.security=DEBUG

jwt.secret=TuSecretoMuyLargoYSeguro1234567890
jwt.expiration=3600000
